export interface FileResponse {
    id: number;
    file_name: string;
    file_type: string;
    file_size: number;
    download_url: string;
}

export interface FileUploadRequest {
    id?: number;          // optional (usually generated by backend)
    file_name: string;
    file_type: string;
    file_size: number;
    file_path: string;
    user_id: number;
    post_id: number;
    message?: string;     // optional caption / message
}

export interface MultipleFileUploadRequest {
    files: FileUploadRequest[];
    message?: string;
}
